### ISSUE TITLE
[juno-pipeline] improve 3rd party integration in the pipeline

### ISSUE THREAD

**Issue by hodanoori** [sapcc/juno#482]
- \[ ] \[build step] It seems that errors with the imports and `jspm` from the 3rd Party apps are causing our pipeline to stumble during the build step blocking again our internal deploymentes.
    
    ```
    (+) greenhouse-cluster-admin@1.0 install external dependency @types/jest@^27.5.2
    JspmError: No '.' exports subpath defined in https://ga.jspm.io/npm:@types/jest@27.5.2/ resolving @types/jest imported from file:///tmp/final/.
        at throwExportNotDefined (file:///juno/node_modules/@jspm/generator/dist/generator-e63a16ef.js:1693:19)
        at Resolver.resolveExport (file:///juno/node_modules/@jspm/generator/dist/generator-e63a16ef.js:1719:44)
        at async TraceMap.resolve (file:///juno/node_modules/@jspm/generator/dist/generator-e63a16ef.js:2935:59)
        at async TraceMap.visit (file:///juno/node_modules/@jspm/generator/dist/generator-e63a16ef.js:2707:26)
        at async Generator.install (file:///juno/node_modules/@jspm/generator/dist/generator-e63a16ef.js:4049:13)
        at async installPackage (file:///juno/ci/scripts/generate_importmap.mjs:217:3)
        at async start (file:///juno/ci/scripts/generate_importmap.mjs:348:25) {
      jspmError: true,
      code: 'MODULE_NOT_FOUND'
    }

    ```
Error to reproduce from jspm:
https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcCipLEgt1s9KLS5xMLLUM9UzNAAAYHwC+iIA

![Image](https://github.com/sapcc/juno/assets/1876079/32443c05-204c-49cc-869c-77ee1ab98deb)

- \[ ] \[test step] Research other "non blocking" alternatives when deploying external apps, ex. limesUI. Due tue an Error in the limesUI is the Juno Pipeline blocked and we can't deploy to production.
 
- \[ ] Check if we can optimize the test step. Right now we are testing all versions of all apps which there were probably already tested in the passt. See example:

    ```
    mount app: {"name":"doop","version":"1.0.1","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.0","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.1","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.10","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.11","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.12","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.2","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.3","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.4","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.5","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.6","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.7","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.8","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.0.9","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.0","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.1","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.2","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.3","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.4","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.1.5","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.2.0","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.2.1","props":{"apiEndpoint":"test"}}
    SUCCESS
    mount app: {"name":"doop","version":"2.2.1","props":{"apiEndpoint":"test"}}
    ```

### dry run step

1. build mini importmap and sources
2. run e2e test with special nginx/cypress images directly within the CI step

## 3.  option with no importmap (ALL IN)

**Comment by andypf** [comment]
Closing this issue due to inactivity. Please reopen if you need further assistance.
